<?php
namespace src\Constant;

class Constant
{
    public const ABLSTR = 'Force';
    public const ABLDEX = 'Dextérité';
    public const ABLCON = 'Constitution';
    public const ABLINT = 'Intelligence';
    public const ABLWIS = 'Sagesse';
    public const ABLCHA = 'Charisme';

    public const FORMNAME = 'formName';
    public const HEROSELECTION = 'heroSelection';
    public const ONGLET = 'onglet';
    public const EDIT = 'edit';
    public const NEW = 'new';
    public const CREATE = 'create';

    public const CLASSES  = 'classes';
    public const HOME     = 'home';
    public const ARMORS   = 'armors';
    public const WEAPONS  = 'weapons';
    public const SPECIES  = 'species';
    public const SPECIE   = 'specie';
    public const GENERAL  = 'general';
    public const EPIC     = 'epic';
    public const COMBAT   = 'combat';
    public const SKILLS   = 'skills';
    public const FEATS    = 'feats';
    public const GEAR     = 'gear';
    public const MONSTERS = 'monsters';
    public const ORIGIN   = 'origin';
    public const ORIGINES = 'origines';
    public const ORIGINS  = 'origins';
    public const SPELLS   = 'spells';
    public const LIGHT    = 'light';
    public const MEDIUM   = 'medium';
    public const HEAVY    = 'heavy';
    public const SHIELD   = 'shield';
    public const DIVERS   = 'divers';
    public const GAMES   = 'games';
    public const MUSIC   = 'music';
    public const TOOLS   = 'outils';
    public const RULES    = 'rules';
    public const OUTERDIVCLASS = 'outerDivClass';
    public const ONG_COMPENDIUM = 'compendium';
    public const TAB_MONSTERS = 'monsters';

    public const CST_EXTRA = '-extra';
    public const CST_ASC = 'ASC';
    public const CST_CLASS = 'class';
    public const CST_ACTIVE = 'active';
    public const CST_CONTENT = 'content';
    public const CST_DESC       = 'DESC';
    public const CST_TYPE = 'type';
    public const CST_AJAXACTION = 'ajaxAction';
    public const CST_FEAT = 'feat';
    public const CST_COLSPAN = 'colspan';
    public const CST_ATTRIBUTES = 'attributes';
    public const CST_DATA       = 'data';
    public const CST_PARENT     = 'parent';
    public const CST_TARGET     = 'target';
    public const CST_TRIGGER    = 'trigger';
    public const CST_ACTION     = 'action';
    public const CST_CLICK      = 'click';
    public const CST_VALUE      = 'value';
    public const CST_OPENMODAL  = 'openModal';
    public const CST_LABEL      = 'label';
    public const CST_LABEL_SING = 'labelSingulier';
    public const CST_NAME       = 'name';
    public const CST_ID         = 'id';
    public const CST_CHECKED    = 'checked';
    public const CST_SELECTED   = 'selected';
    public const CST_TITLE      = 'title';
    public const CST_NEXT       = 'next';
    public const CST_PREV       = 'prev';
    public const CST_SLUG       = 'slug';
    public const CST_MARTIAL    = 'martial';
    public const CST_SIMPLE     = 'simple';
    public const CST_MELEE      = 'melee';
    public const CST_RANGED     = 'ranged';
    public const CST_EXTRA_PREREQUIS = 'extraprerequis';
    public const CST_VUE        = 'vue';
    public const CST_CONTACT    = 'contact';
    public const CST_ILLIM      = 'illim';
    public const CST_PERSO      = 'perso';
    public const CST_SPECIALES  = 'spec';

    public const CST_ABILITIES   = 'abilities';
    public const CST_SKILLS      = 'skills';
    public const CST_ITEMS       = 'items';
    public const CST_TOOL        = 'tool';
    public const CST_GEAR        = 'gear';
    public const CST_ARMOR       = 'armor';
    public const CST_WEAPON      = 'weapon';
    public const CST_TOOLS       = 'tools';
    public const CST_SUBSKILLS   = 'subSkills';
    public const CST_FEATNAME    = 'featname';
    public const CST_TOOLNAME    = 'toolname';
    public const CST_TOOLSLUG    = 'toolSlug';
    public const CST_FEATSLUG    = 'featSlug';
    public const CST_FEATTYPE    = 'featType';
    public const CST_TYPELABEL   = 'typeLabel';
    public const CST_EQUIPMENT   = 'equipement';
    public const CST_DESCRIPTION = 'description';
    public const CST_CREATURE_TYPE = 'type_de_creature';
    public const CST_SIZE_CATEGORY = 'categorie_de_taille';
    public const CST_SPEED        = 'vitesse';
    public const CST_POWERS       = 'powers';
    public const CST_PREREQUIS    = 'prerequis';
    public const CST_PREREQUIS_NIV4 = ' (prérequis : niveau 4 ou supérieur';
    public const CST_PREREQUIS_ASDC = ' (prérequis : aptitude Style de combat)';
    public const CST_PREREQUIS_NIV19 = ' (prérequis : niveau 19 ou supérieur';

    public const CST_EMPTY_SPAN = '<span></span>';
    public const CST_VIDE       = '&nbsp;';

    /////////////////////////////////////////////////
    // Pagination
    public const CST_CURPAGE            = 'curpage';
    public const CST_DISABLED           = 'disabled';
    public const CST_HREF               = 'href';
    public const PAGE_OPT_SIMPLE        = 'simple';
    public const PAGE_OPT_NUMBERS       = 'numbers';
    public const PAGE_OPT_SMP_NMB       = 'simple_numbers';
    public const PAGE_OPT_FULL          = 'full';
    public const PAGE_OPT_FULL_NMB      = 'full_numbers';
    public const PAGE_OPT_FST_LAST_NMB  = 'first_last_numbers';
    public const PAGE_NBPERPAGE         = 'nbPerPage';
    public const PAGE_DEFAULT_NBPERPAGE = '10';
    public const PAGE_OPTION            = 'option';
    public const PAGE_OBJS              = 'objs';
    public const PAGE_QUERY_ARG         = 'queryArg';
    public const PAGE_PREVIOUS          = '&lsaquo;';
    public const PAGE_NEXT              = '&rsaquo;';
    public const PAGE_FIRST             = '&laquo;';
    public const PAGE_LAST              = '&raquo;';
    public const PAGE_WIDTH             = 'pageWidth';
}
